name: first_profile
description: "A new Flutter project."

publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Font Awesome icons package
  font_awesome_flutter: ^10.1.0

  # Cupertino Icons font for iOS-style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints for Flutter code
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add assets to your application
  assets:
    - images/haile.jpg

  # Add custom fonts

  # Add icons package (already included in dependencies section)
